import { useEffect, useState } from 'react'
import { CheckCircle2, Download, FileDown } from 'lucide-react'
import { useBackupRecoveryStore } from '../store/backupRecoveryStore'
import { EXPORT_FORMATS, EXPORT_MODULES } from '../services/backupRecoveryService'
import PageHeaderSimple from '../components/PageHeaderSimple'
import GlassCard from '../../../../components/common/GlassCard'
import DataTable from '../../../../components/common/DataTable'
import Skeleton from '../../../../components/common/Skeleton'
import ErrorState from '../../../../components/common/ErrorState'
import EmptyState from '../../../../components/common/EmptyState'
import { PrimaryButton } from '../../../../components/common/Button'
import { formatDate } from '../../../../utils/formatDate'

const selectClass =
  'rounded-xl border border-slate-200 bg-white/80 px-3.5 py-2.5 text-sm text-slate-900 shadow-clay-inset transition-colors duration-200 focus:border-brand-500 focus:outline-none dark:border-white/10 dark:bg-slate-900/60 dark:text-slate-100'

export default function DataExport() {
  const historyStatus = useBackupRecoveryStore((state) => state.exportHistoryStatus)
  const historyError = useBackupRecoveryStore((state) => state.exportHistoryError)
  const exportHistory = useBackupRecoveryStore((state) => state.exportHistory)
  const exportActionStatus = useBackupRecoveryStore((state) => state.exportActionStatus)
  const exportActionError = useBackupRecoveryStore((state) => state.exportActionError)
  const fetchExportHistory = useBackupRecoveryStore((state) => state.fetchExportHistory)
  const createExport = useBackupRecoveryStore((state) => state.createExport)
  const resetExportActionStatus = useBackupRecoveryStore((state) => state.resetExportActionStatus)

  const [module, setModule] = useState(EXPORT_MODULES[0])
  const [format, setFormat] = useState(EXPORT_FORMATS[0])
  const [dateFrom, setDateFrom] = useState('')
  const [dateTo, setDateTo] = useState('')

  useEffect(() => {
    fetchExportHistory()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (exportActionStatus === 'success') {
      const timeout = setTimeout(() => resetExportActionStatus(), 4000)
      return () => clearTimeout(timeout)
    }
  }, [exportActionStatus, resetExportActionStatus])

  async function handleSubmit(event) {
    event.preventDefault()
    await createExport({ module, format, dateFrom, dateTo })
  }

  const columns = [
    { key: 'module', header: 'Module' },
    { key: 'format', header: 'Format' },
    { key: 'generatedBy', header: 'Generated By' },
    { key: 'generatedAt', header: 'Date', render: (row) => formatDate(row.generatedAt) },
    {
      key: 'actions',
      header: 'Actions',
      render: (row) => (
        <button
          type="button"
          aria-label={`Download ${row.module} export`}
          className="inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs font-semibold text-brand-600 transition-colors duration-200 hover:bg-brand-50 dark:text-brand-300 dark:hover:bg-brand-500/10"
        >
          <Download className="h-3.5 w-3.5" aria-hidden="true" />
          Download
        </button>
      ),
    },
  ]

  return (
    <div className="flex flex-col gap-6">
      <PageHeaderSimple title="Data Export" />

      <div aria-live="polite" className="sr-only">
        {exportActionStatus === 'success' && 'Export generated successfully.'}
        {exportActionStatus === 'error' && `Export failed. ${exportActionError ?? ''}`}
      </div>

      <GlassCard title="Generate New Export" description="Export institutional data for offline analysis, audits or migrations.">
        <form onSubmit={handleSubmit} className="flex flex-col gap-5">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div className="flex flex-col gap-1.5">
              <label htmlFor="export-module" className="text-xs font-medium text-slate-700 dark:text-slate-200">
                Module
              </label>
              <select id="export-module" value={module} onChange={(event) => setModule(event.target.value)} className={selectClass}>
                {EXPORT_MODULES.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </div>

            <div className="flex flex-col gap-1.5">
              <label htmlFor="export-format" className="text-xs font-medium text-slate-700 dark:text-slate-200">
                Format
              </label>
              <select id="export-format" value={format} onChange={(event) => setFormat(event.target.value)} className={selectClass}>
                {EXPORT_FORMATS.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </div>

            <div className="flex flex-col gap-1.5">
              <label htmlFor="export-date-from" className="text-xs font-medium text-slate-700 dark:text-slate-200">
                From
              </label>
              <input id="export-date-from" type="date" value={dateFrom} onChange={(event) => setDateFrom(event.target.value)} className={selectClass} />
            </div>

            <div className="flex flex-col gap-1.5">
              <label htmlFor="export-date-to" className="text-xs font-medium text-slate-700 dark:text-slate-200">
                To
              </label>
              <input id="export-date-to" type="date" value={dateTo} onChange={(event) => setDateTo(event.target.value)} className={selectClass} />
            </div>
          </div>

          {exportActionStatus === 'success' && (
            <p className="flex items-center gap-2 text-sm font-medium text-emerald-600 dark:text-emerald-400">
              <CheckCircle2 className="h-4 w-4 shrink-0" aria-hidden="true" />
              Export generated successfully — see it in the history below.
            </p>
          )}
          {exportActionStatus === 'error' && (
            <p role="alert" className="text-sm font-medium text-red-600 dark:text-red-400">
              {exportActionError}
            </p>
          )}

          <div>
            <PrimaryButton type="submit" fullWidth={false} isLoading={exportActionStatus === 'loading'}>
              <FileDown className="h-4 w-4" aria-hidden="true" />
              Export
            </PrimaryButton>
          </div>
        </form>
      </GlassCard>

      <GlassCard title="Export History" description="Previously generated exports, available for re-download.">
        {historyStatus === 'loading' || historyStatus === 'idle' ? (
          <div className="space-y-2">
            {Array.from({ length: 4 }).map((_, index) => (
              <Skeleton key={index} className="h-12" />
            ))}
          </div>
        ) : historyStatus === 'error' ? (
          <ErrorState message={historyError} onRetry={fetchExportHistory} />
        ) : exportHistory.length === 0 ? (
          <EmptyState icon={FileDown} title="No exports yet" description="Exports you generate will be listed here for re-download." />
        ) : (
          <DataTable columns={columns} rows={exportHistory} />
        )}
      </GlassCard>
    </div>
  )
}
